import express from 'express';
import serverless from 'serverless-http';
// @ts-ignore dist/apollo-app.js is generated by tsc during the build step
import { createApp } from '../dist/apollo-app.js';

let handler: ReturnType<typeof serverless> | null = null;

async function graphqlHandler(req: any, res: any) {
  try {
    if (!handler) {
      console.log('[api/graphql] initializing handler');
      const app = await createApp();
      console.log('[api/graphql] app created');
      handler = serverless(app);
      console.log('[api/graphql] serverless handler created');
    }
    return handler(req, res);
  } catch (err: any) {
    console.error('[api/graphql] init error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: err?.message ?? 'Internal server error' });
    }
  }
}

export default graphqlHandler;

const port = process.env.PORT ?? 7071;
const serverApp = express();
serverApp.use(graphqlHandler);
serverApp.listen(port, () => console.log(`Server listening on port ${port}`));
